### ISSUE TITLE
Register API Endpoint to consul

### ISSUE THREAD

**Issue by brahama** [zephrax/serverless-consul-variables#3]
Lets discuss on how useful could it be to register the API GW endpoint to consul as a service so we can use it from other providers like Terraform.
It would be nice to do HealthChecks also as it comes out of the box with consul. But not so sure about it.

**Comment by brahama** [comment]
Working on it. Will submit the first PR for this now

**Comment by zephrax** [comment]
I merged your PR & did some fix. I'm closing this issue :)
